Remove build files and let travis build those. (#198)
* Remove files created during the build.

Signed-off-by: Marcin Pasinski <marcin.pasinski@mender.io>

* Add travis build option and fix `lodash.differencewith` dependency.

Add missing packages (match and serve).
Fix 'differenceWith' require to use lowercase letters.

Signed-off-by: Marcin Pasinski <marcin.pasinski@mender.io>

* Update react-router package to contain match.js

This is fixing gulp building issue.

Signed-off-by: Marcin Pasinski <marcin.pasinski@mender.io>

* Fix gulp 'makeSelectable' building issue.

Fix gulp error 'Error: Cannot find module './List/makeSelectable' '

Signed-off-by: Marcin Pasinski <marcin.pasinski@mender.io>